version: "2.0"

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    volumes:
      - ".:/app"
    depends_on:
      - db

  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
