name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        working-directory: ./aplicacao
        run: docker-compose up --build -d

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint
        working-directory: ./aplicacao
        run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level F"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        working-directory: ./aplicacao
        run: docker-compose run app bash -c "rails db:reset;rspec
