name: Docker Image CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

defaults:
  run:
    working-directory: ./aplicacao

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: docker-compose up --build -d

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        run: docker-compose run app bash -c "gem install rubocop; rubocop --fail-level error -F"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: docker-compose run app bash -c "rake db:reset;rspec"

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
      - name: Publish
        run: |
          heroku container:push web -a $APP_NAME
          heroku container:release web -a $APP_NAME
